### ISSUE TITLE
Detect phone numbers and make them clickable

### ISSUE THREAD

**Issue by Studio384** [optimise-group/click-for-yealink#14]
The extension should be able to recognize phone numbers on webpages and make them into clickable URIs.

#### Features
- [x] Detect phone numbers
- [x] When a phone number is already clickable, don't try to make it clickable again (it currently nests an anchor within an anchor)
- [x] Support multiple phone numbers within the same node
- [x] Detect `tel:`-urls that don't have phone numbers as their text node.

### General enhancements
- [x] We currently create some artificial empty nodes in the loop and than destroy them again... It shouldn't do that.

**Comment by timothyvanderaerden** [comment]
Do you mean `tel` links? Are these `tel` links already supported by the extension? If so I wouldn't do anything special with them.

**Comment by Studio384** [comment]
I mean any links. If a phone number happens to be included in any anchor tag, regardless of what it links to. The extension doesn't handle `tel`-anchors. I'm not sure that can be done by a browser extension since (at least in Windows) that's an OS level-configuration. We'd have to replace the `href` to make that work, and I'm not sure that is desired behavior (for example: if the phone number is part of a link that doesn't actually link to the phone number but to a contact page, we shouldn't be removing that link).

**Comment by timothyvanderaerden** [comment]
Are there any phone numbers that have links which are not `tel`-anchors?
Since we make phone numbers clickable it would seem weird to users that some phone numbers suddenly are not handled by the extension when they have a `tel`-anchor. Can we make it an option to rewrite the `href` if it is a `tel`? That way we leave it up to the user.
